// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScaleUP.Services.NBFCAPI.Persistence;

#nullable disable

namespace ScaleUP.Services.NBFCAPI.Migrations
{
    [DbContext(typeof(NBFCApplicationDbContext))]
    [Migration("20240105185258_5Jan")]
    partial class _5Jan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScaleUP.Services.NBFCModels.Master.OfferSelfConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCibilScore")
                        .HasColumnType("int");

                    b.Property<double>("MaxCreditLimit")
                        .HasColumnType("float");

                    b.Property<int>("MaxVintageDays")
                        .HasColumnType("int");

                    b.Property<int>("MinCibilScore")
                        .HasColumnType("int");

                    b.Property<double>("MinCreditLimit")
                        .HasColumnType("float");

                    b.Property<int>("MinVintageDays")
                        .HasColumnType("int");

                    b.Property<double>("MultiPlier")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("OfferSelfConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
